grafana_url: http://localhost:8081
dashboard_uid: grid_search_dashboard
folders:
  4-Workers:
    from: 1700111859229
    to: 1700112759229
  8-Workers:
    from: 1700115459229
    to: 1700116359229
  16-Workers:
    from: 1700119059229
    to: 1700119959229
panels:
  - CPU Usage (Workers)
  - Memory Usage (Workers)
  - Network Usage (Workers)
  - Disk Usage (Workers)
  - Per node throughput
  - Combined throughput
  - Coefficient of variation
size:
  width: 1000
  height: 400
theme: light


